name: Build and Release APK

on:
  push:
    branches:
      - master
      - 'saleh/test-rebase'
      - 'saleh/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history to create and push tags

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk

      - name: Create Tag
        id: create_tag
        run: |
          TAG="release-${GITHUB_RUN_NUMBER}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          # Configure Git so we can push the tag
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag: ${{ env.TAG }}
          files: app-release-apk/app-release.apk
