name: Build and Release APK

on:
  push:
    branches:
      - master
      - 'saleh/test-rebase'
      - 'saleh/**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      apk_path: build/app/outputs/flutter-apk/app-release.apk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # Optionally, you can set a tag name or release name here.
          # The release is created against the commit that triggered the workflow.
          files: app-release-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
